# This line is crucial for Render to correctly interpret the file.
version: "1"

services:
  # Defines the web service to be deployed.
  - name: futbol-api
    type: web
    plan: free # Use the free plan to avoid charges.
    env: image # Tells Render to use a pre-built Docker image.
    autoDeploy: false # Disables auto-deploy, we control it with the Deploy Hook.
    image:
      url: ghcr.io/unq-dapp-grupom/scraper-service:main # URL of the image in GitHub Container Registry
    healthCheckPath: /actuator/health # Path for Render to know if your app is ready.
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production # Activates the Spring production profile.