# --- Configuration for the 'dev' development profile ---
scraper.api.key=JOBP2R4CIZ6D6OFOIOKQ8F8XJ651903DKXG00N6WRHWI595AXVNAKTWNO7SP9572FTJ4VR031FYF54NU

# Datasource configuration for HSQLDB ('dev' profile)
spring.datasource.url=jdbc:hsqldb:file:./data/scraperdb;shutdown=true
spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate configuration for HSQLDB
spring.jpa.database-platform=org.hibernate.dialect.HSQLDialect
# This will create/update the database schema on startup.
# Useful for development.
spring.jpa.hibernate.ddl-auto=update

# Enable the H2/HSQLDB console to view the database in the browser
spring.h2.console.enabled=true
# The path to access the console (e.g., http://localhost:8081/h2-console)
spring.h2.console.path=/h2-console

# Format JSON in responses
spring.jackson.serialization.indent-output=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null
