# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://dpg-d3s0aru3jp1c73eig2m0-a.oregon-postgres.render.com:5432/scraperdb_nxrd
spring.datasource.username=scraper_user
spring.datasource.password=ekPP3d8tBRwVxULT5PWQQ2RtLvLAb7zl

# JPA + SQL Initialization
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Connection pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000

# Logging temporal para debug
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG