# --- Configuración para el entorno LOCAL ---
scraper.api.key=WLQBX1N40MPXIZGYOPZU6DNCSOQHXITLIWUJHTHQNHZJTELM85KNEXINBIXX2B1PUD947JH7JA1FLVZ5
scraper.timeout=60000
scraper.max.retries=2

# Cache configuration
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=1h

