# PostgreSQL configuration - NUEVA DB
spring.datasource.url=jdbc:postgresql://dpg-d3skdnndiees73cktdj0-a.oregon-postgres.render.com:5432/scraperdb_0mqf
spring.datasource.username=scraper_user
spring.datasource.password=XZTN9GjbKJtIjMnuLB29aYvRuPuH0EJl

# JPA Configuration - CREAR TODO DESDE CERO
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true

# SQL Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Logging para ver la creación
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG